// Generated by tools/build-people.js. Do not edit.
window.GL_PEOPLE = [
  {
    "id": "0xalex-alexandre",
    "name": "0xAlex (Alexandre)",
    "role": "Integration Lead",
    "company": "Kleros",
    "tags": [
      "guest"
    ]
  },
  {
    "id": "albert-castellana",
    "name": "Albert Castellana",
    "role": "CEO & Cofounder",
    "company": "GenLayer Labs",
    "tags": [
      "team"
    ]
  },
  {
    "id": "ana-maria",
    "name": "Ana Maria",
    "role": "Cohost & Events Core",
    "company": "GenLayer",
    "tags": [
      "team"
    ]
  },
  {
    "id": "armagan-amcalar",
    "name": "Armagan Amcalar",
    "role": "CTO",
    "company": "OpenServ",
    "tags": [
      "guest"
    ]
  },
  {
    "id": "david-riudor",
    "name": "David Riudor",
    "role": "Chief Institutional Officer",
    "company": "GenLayer Foundation",
    "tags": [
      "team"
    ]
  },
  {
    "id": "edgars-nemse",
    "name": "Edgars Nemše",
    "role": "CEO",
    "company": "GenLayer Foundation",
    "tags": [
      "team"
    ]
  },
  {
    "id": "ivan-raskovsky",
    "name": "Ivan Raskovsky",
    "role": "Head of Ecosystem",
    "company": "GenLayer Foundation",
    "tags": [
      "team"
    ]
  },
  {
    "id": "joaquin-bressan",
    "name": "Joaquin Bressan",
    "role": "Founding Engineer",
    "company": "GenLayer Foundation",
    "tags": [
      "team"
    ]
  },
  {
    "id": "rahul-sethuram",
    "name": "Rahul Sethuram",
    "role": "Head of AI",
    "company": "LiFi",
    "tags": [
      "guest"
    ]
  },
  {
    "id": "ryan-mcpeck",
    "name": "Ryan McPeck",
    "role": "Head of Smart Accounts",
    "company": "Metamask",
    "tags": [
      "guest"
    ]
  }
];
window.GL_PEOPLE_PHOTOS = {};
