// Inlines the brand woff2 files into js/fonts.js as base64 @font-face rules.
// Inlined (not linked) so the PNG export can embed them, including when the app is opened from disk.
// Run: node tools/build-fonts.js
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

const faces = [
  { family: 'F37 Lineca VF', file: 'F37Lineca-VF.woff2', weight: '10 900' },
  { family: "Suisse Int'l", file: 'SuisseIntl-Regular.woff2', weight: '400' },
  { family: "Suisse Int'l Mono", file: 'SuisseIntlMono-Regular.woff2', weight: '400' },
  // Agent Tank display faces (trial cuts, cleared for the hackathon material).
  { family: 'GL Druk', file: 'DrukSuper-Trial.woff2', weight: '400' },
  { family: 'GL Druk Wide', file: 'DrukWideSuper-Trial.woff2', weight: '400' },
];

const css = faces.map(({ family, file, weight }) => {
  const b64 = fs.readFileSync(path.join(root, 'fonts', file)).toString('base64');
  return `@font-face{font-family:"${family}";font-weight:${weight};font-style:normal;font-display:block;src:url(data:font/woff2;base64,${b64}) format("woff2");}`;
}).join('\n');

const js = `// Generated by tools/build-fonts.js. Do not edit.
window.GL_FONT_CSS = ${JSON.stringify(css)};
document.head.appendChild(Object.assign(document.createElement('style'), { textContent: window.GL_FONT_CSS }));
`;
fs.writeFileSync(path.join(root, 'js', 'fonts.js'), js);
console.log('js/fonts.js', (js.length / 1024).toFixed(0) + ' KB');
