// Builds the shared people list from the person files in people/*.json.
// A person file is what the app's "Download person file" produces: name, role, company, tags
// and the processed photo. Output: js/people-index.js (text only, loaded up front) and one
// people/data/<id>.js per person (the photo, loaded when that person is picked).
// Photos ship as data URLs inside scripts because the PNG export needs the pixels inline and
// neither fetch() nor canvas reads of image files work when the page is opened from disk.
// Run: node tools/build-people.js
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '..', 'people');

const people = fs.readdirSync(dir)
  .filter((file) => file.endsWith('.json'))
  .map((file) => JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')))
  .sort((a, b) => a.name.localeCompare(b.name));

fs.rmSync(path.join(dir, 'data'), { recursive: true, force: true });
fs.mkdirSync(path.join(dir, 'data'));
for (const person of people) {
  fs.writeFileSync(
    path.join(dir, 'data', person.id + '.js'),
    `window.GL_PEOPLE_PHOTOS[${JSON.stringify(person.id)}] = ${JSON.stringify(person.photo)};\n`
  );
}

const index = people.map(({ id, name, role, company, tags }) => ({ id, name, role, company, tags }));
fs.writeFileSync(
  path.join(__dirname, '..', 'js', 'people-index.js'),
  `// Generated by tools/build-people.js. Do not edit.\nwindow.GL_PEOPLE = ${JSON.stringify(index, null, 2)};\nwindow.GL_PEOPLE_PHOTOS = {};\n`
);
console.log(people.length + ' people');
